import { title } from "process"
import 'tailwindcss/tailwind.css';
import styles from '../app/home.module.css'
import Head from 'next/head';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-gray-50">
      <Head>
        <title>My Roommate</title>
      </Head>
      <body className="overflow-y-hidden bg-gray-50">
        {children}</body >
    </html>
  )
}
